name: Ntfy-Notification

on:
  workflow_run:
    workflows: [Build Rust project]
    types:
      - completed

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Successfull message
        run: |
          curl \
          -u ${{ secrets.NTFY_CRED }} \
          -H "Title: Rigit compiled successfully" \
          -H "Content-Type: text/plain" \
          -d $'Repo: ${{ github.repository }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ github.event.workflow_run.conclusion }}' \
          ${{ secrets.NTFY_URL }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Failed message
        run: |
          curl \
          -u ${{ secrets.NTFY_CRED }} \
          -H "Title: Rigit Compilation failed" \
          -H "Content-Type: text/plain" \
          -d $'Repo: ${{ github.repository }}\nCommit: ${{ github.sha }}\nRef: ${{ github.ref }}\nStatus: ${{ github.event.workflow_run.conclusion }}' \
          ${{ secrets.NTFY_URL }}
